[package]
name = "jingtum_lib"
version = "0.1.0"
authors = ["beautifularea <beautifularea@gmail.com>"]
edition = "2018"

[dependencies]
websocket = "0.22.4"
hyper = "^0.10.6"
sha1 = "0.6"
base64 = "0.10.0"
futures = "0.1"
tokio = "0.1.14"
tokio-executor = { version = "0.1.0", optional = true }
tokio-io = "0.1"
tokio-reactor = { version = "0.1", optional = true }
tokio-tcp = { version = "0.1", optional = true }
tokio-threadpool = { version = "0.1.3", optional = true }
tokio-timer = { version = "0.2", optional = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"