
[package]
license = "MIT"
name = "jlib"
readme = "README.md"
repository = "https://github.com/zTgx/jlib.git"
version = "0.0.1"

[dependencies]
sha1 = "0.6"
futures = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ws = "0.8.1"
log = "0.4.0"
env_logger = "0.6.1"
rand = "0.6"
ring = "0.14.6"
secp256k1 = "0.13.0"
num = "0.2"
compare = "0.1"
rust-crypto = "^0.2"
hex = "0.3.2"
ed25519-dalek = "0.9.1"
byteorder = "1.3.2"
lazy_static = "1.3.0"
typename = "0.1.1"
ryu = "1.0"
void = "1.0.2"
url = "1.7.2"
basex-rs = { git = "https://github.com/zTgx/basex-rs.git" }
