[package]
name = "jingtum_lib"
version = "0.1.0"
authors = ["beautifularea <beautifularea@gmail.com>"]
edition = "2018"

[dependencies]
websocket = "0.22.4"
hyper = "^0.10.6"
sha1 = "0.6"
base64 = "0.10.0"
futures = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ws = "*"